"""The lo2024 Curriculum, loaded once from lo2024.json (regenerated by
scripts/extract_curriculum.py) and held in memory; there is no table."""

import json
from importlib.resources import files
from typing import Literal

from pydantic import BaseModel, field_validator

GeneralRequirement = Literal["I", "II", "III", "IV"]
_DATA = json.loads(files("classlop.items").joinpath("lo2024.json").read_text("utf-8"))
_IDS = frozenset(t["id"] for s in _DATA["sections"] for t in s["topics"])


class CurriculumTopic(BaseModel):
    id: str
    name: str  # Polish, as the Student reads it

    @field_validator("id")
    @classmethod
    def _known(cls, id: str) -> str:
        if id not in _IDS:
            raise ValueError(f"{id} is not a Curriculum topic")
        return id


class CurriculumSection(BaseModel):
    id: str
    name: str
    topics: list[CurriculumTopic]


class GeneralRequirementText(BaseModel):
    id: GeneralRequirement
    name: str
    description: str


_SECTIONS = [
    CurriculumSection(
        id=s["id"],
        name=s["name"],
        topics=[CurriculumTopic(id=t["id"], name=t["name"]) for t in s["topics"]],
    )
    for s in _DATA["sections"]
]
_GENERAL = [GeneralRequirementText.model_validate(g) for g in _DATA["general_requirements"]]


def curriculum() -> list[CurriculumSection]:
    """Every Curriculum section with its topics, in the act's order."""
    return list(_SECTIONS)


def general_requirements() -> list[GeneralRequirementText]:
    """The four General requirements, I to IV."""
    return list(_GENERAL)
