#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then value="${value:1:${#value}-2}"; value="${value//"$sq"/\'}"; fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Classlop demo tenant (issue #4). Values, including the Teacher and
# Student passwords, land in the gitignored .env; the admin password never does.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "$0")/.."
TOTAL_STAGES=10
GRAPH_EXPLORER="https://developer.microsoft.com/en-us/graph/graph-explorer"

banner "Classlop demo tenant"

stage "Sign up for a tenant"
say "First choice: an Office 365 A1 Education trial (gives the Education Assignments API)."
open_url "https://www.microsoft.com/education/products/office"
step "Enter your school email address and select 'Get started'."
step "Follow the sign-up screens (not documented by Microsoft, so read them carefully)."
step "If an eligibility verification wizard asks for the school domain, you may close it:"
note "  the trial works right away; verification only matters to convert after 30 days."
warn "Timebox: one hour. If sign-up rejects the email or drops you into an existing"
warn "school tenant as an ordinary user, answer 'n' below to use the business trial."
if confirm "Did A1 sign-up finish with you signed in to a new tenant?"; then
  M365_TENANT_KIND=edu
else
  M365_TENANT_KIND=business
  say "Fallback: Microsoft 365 for business, 30-day trial (Lessons and Attendance work unchanged)."
  open_url "https://www.microsoft.com/microsoft-365/business/microsoft-365-business-basic"
  step "Select 'Try free for one month' (Business Basic is enough: Teams, Exchange, OneDrive)."
  warn "The '<name>.onmicrosoft.com' domain you pick during sign-up can never be changed."
  step "Follow the account set-up steps."
  warn "Afterwards: Billing > Your products > turn off recurring billing, or it converts to paid."
  pause "Press Enter once the business trial tenant exists."
fi
write_env M365_TENANT_KIND "$M365_TENANT_KIND"
pause

stage "Confirm you are Global Admin"
open_url "https://admin.cloud.microsoft"
step "Users > Active users > select yourself > Roles: it must say Global Administrator."
step "Note the '.onmicrosoft.com' domain under Settings > Domains."
if ! confirm "Are you Global Administrator of this tenant?"; then
  warn "Without Global Admin you cannot grant consent. Re-run and answer 'n' at stage 1."
  exit 1
fi
ask M365_TENANT_DOMAIN "Tenant domain (e.g. classlopdemo.onmicrosoft.com):"
write_env M365_TENANT_DOMAIN "$M365_TENANT_DOMAIN"
pause

stage "Create the Teacher and two Students"
say "Invented people only: this repo is public."
open_url "https://admin.cloud.microsoft"
step "Users > Active users > Add a user (Simplified view: the 'Add user' button)."
step "Create teacher.demo, student.a and student.b on the onmicrosoft.com domain."
if [[ "$M365_TENANT_KIND" == edu ]]; then
  step "Licence: 'Office 365 A1 for faculty' for the Teacher, 'A1 for students' for both Students."
else
  step "Licence: the business trial licence for all three."
fi
step "Keep 'Require this user to change their password' on; copy each temporary password."
warn "Keep the admin password outside the repo folder, e.g. in your browser's password manager."
note "Teacher and Student passwords go in .env; update them there after each first sign-in."
ask M365_TEACHER_UPN "Teacher sign-in address:"
ask M365_STUDENT_UPNS "Student sign-in addresses, comma separated:"
ask_secret M365_TEACHER_PASSWORD "Teacher password:"
ask_secret M365_STUDENT_PASSWORDS "Student passwords, comma separated:"
write_env M365_TEACHER_UPN "$M365_TEACHER_UPN"
write_env M365_STUDENT_UPNS "$M365_STUDENT_UPNS"
write_env M365_TEACHER_PASSWORD "$M365_TEACHER_PASSWORD"
write_env M365_STUDENT_PASSWORDS "$M365_STUDENT_PASSWORDS"
pause

stage "Create the Class team as the Teacher"
open_url "https://teams.microsoft.com"
step "Use a private browser window and sign in as $M365_TEACHER_UPN (set a new password, put it in .env)."
if [[ "$M365_TENANT_KIND" == edu ]]; then
  step "Teams > create a team > choose the 'Class' type (labels unverified, look for 'Class')."
  note "  No 'Class' type yet? Licences can take a while to apply; wait and reload."
else
  step "Teams > create a team > from scratch > Private (no Class type on a business tenant)."
fi
step "Name it after an invented Class, e.g. '2B Matematyka', and add both Students."
ask M365_CLASS_NAME "Class team name:"
write_env M365_CLASS_NAME "$M365_CLASS_NAME"
pause

stage "Register the Classlop app"
open_url "https://entra.microsoft.com"
step "Sign in as the admin. Entra ID > App registrations > New registration."
step "Name: 'Classlop dev'. Supported account types: 'Single tenant only'. Select Register."
step "On the Overview page copy 'Application (client) ID' and 'Directory (tenant) ID'."
ask M365_CLIENT_ID "Application (client) ID:"
ask M365_TENANT_ID "Directory (tenant) ID:"
write_env M365_CLIENT_ID "$M365_CLIENT_ID"
write_env M365_TENANT_ID "$M365_TENANT_ID"
pause

stage "Make it a confidential Web client (the Teacher signs in to Classlop)"
step "In Classlop dev: Manage > Authentication > Add a platform > 'Web'."
step "Add the redirect URI exactly: http://localhost:8000/auth/callback > Configure."
step "Manage > Certificates & secrets > Client secrets > New client secret > Add."
step "Copy its 'Value' now: it is shown only once."
ask_secret M365_CLIENT_SECRET "Client secret value:"
write_env M365_CLIENT_SECRET "$M365_CLIENT_SECRET"
pause

stage "Grant Graph permissions"
step "In Classlop dev: API permissions > Add a permission > Microsoft Graph > Delegated permissions."
step "Add: User.Read, OnlineMeetings.ReadWrite, OnlineMeetingArtifact.Read.All, Calendars.ReadWrite, Files.Read.All"
step "and, for the teams area: Group.ReadWrite.All, TeamMember.ReadWrite.All, Channel.ReadBasic.All,"
step "Team.Create, User.ReadBasic.All"
if [[ "$M365_TENANT_KIND" == edu ]]; then
  step "and: EduRoster.ReadBasic, EduAssignments.ReadWrite"
else
  step "and: GroupMember.Read.All, Team.ReadBasic.All"
fi
step "Select 'Grant admin consent for <tenant>' > Yes > Refresh."
step "Every row must show 'Granted for <tenant>'."
pause "Press Enter once consent shows as granted."

stage "Admit the Teacher"
open_url "https://entra.microsoft.com"
step "Entra ID > Users > $M365_TEACHER_UPN > Overview: copy 'Object ID'."
note "Only this account may sign in to Classlop."
ask M365_TEACHER_OID "Teacher's object ID:"
write_env M365_TEACHER_OID "$M365_TEACHER_OID"
if ! _existing SESSION_KEY >/dev/null; then
  write_env SESSION_KEY "$(head -c 32 /dev/urandom | base64 | tr -d '\n')"
fi
pause

stage "Smoke check: find the Class through Graph"
open_url "$GRAPH_EXPLORER"
if [[ "$M365_TENANT_KIND" == edu ]]; then
  step "Sign in as the admin. Modify permissions: consent EduRoster.ReadBasic, ticking"
  step "'Consent on behalf of your organization' if offered. Then sign out."
  step "Sign in as $M365_TEACHER_UPN and run: GET https://graph.microsoft.com/v1.0/education/me/taughtClasses"
  step "Copy the 'id' of '$M365_CLASS_NAME'."
  warn "Error or empty list? The Education API is not working; record that on issue #4."
else
  step "Sign in as $M365_TEACHER_UPN. Modify permissions: consent Team.ReadBasic.All"
  note "  'Need admin approval'? Consent it as the admin on behalf of your organization first."
  step "Run: GET https://graph.microsoft.com/v1.0/me/joinedTeams"
  step "Copy the 'id' of '$M365_CLASS_NAME'."
fi
ask M365_CLASS_ID "Class id:"
write_env M365_CLASS_ID "$M365_CLASS_ID"
pause

stage "Facts for issue #4"
say "Paste this into the resolution comment on 'Create the demo tenant'. No secrets in it."
printf '\n'
cat <<FACTS
  - Tenant: $M365_TENANT_KIND trial, $M365_TENANT_DOMAIN (created $(date +%F), expires after 30 days)
  - Tenant ID: $M365_TENANT_ID
  - App registration: 'Classlop dev', client ID $M365_CLIENT_ID, Web client, redirect http://localhost:8000/auth/callback
  - Teacher: $M365_TEACHER_UPN; Students: $M365_STUDENT_UPNS
  - Class team: '$M365_CLASS_NAME' ($M365_CLASS_ID)
  - Passwords: Teacher and Students in each dev's gitignored .env (M365_TEACHER_PASSWORD,
    M365_STUDENT_PASSWORDS), shared by the tenant admin in a private message; the admin
    password stays outside the repo. IDs above live in .env too (copy the M365_* keys).
FACTS
printf '\n'
pause "Press Enter once copied."

finish
